/******************************************************************************
*
*   COPYRIGHT (C) ACTIA  2012
*
*   Toute reproduction de ce document même partielle, est strictement interdite
*   sans autorisation écrite
*
*   Version     : V1.00
*   Date        : 18/09/14
*   Evolution   : PCou Straton Multic 2
******************************************************************************/

//*************************************************************************
//   DEFINITION
//*************************************************************************

//*************************************************************************
//   MACRO
//*************************************************************************

//*************************************************************************
//   TYPEDEF
//*************************************************************************

//*************************************************************************
//   EXPORT
//*************************************************************************

//*************************************************************************
//   PROTO
//*************************************************************************
T5_DWORD BEEP_CONTROL  (T5_WORD wCommand, T5PTR_DB pBase, T5_PTR pClass, T5_PTR pInst, T5_PTWORD pArgs);
T5_DWORD BEEP_VOL  (T5_WORD wCommand, T5PTR_DB pBase, T5_PTR pClass, T5_PTR pInst, T5_PTWORD pArgs);
T5_DWORD BEEP_PlayBeep  (T5_WORD wCommand, T5PTR_DB pBase, T5_PTR pClass, T5_PTR pInst, T5_PTWORD pArgs);
T5_DWORD BEEP_STOP  (T5_WORD wCommand, T5PTR_DB pBase, T5_PTR pClass, T5_PTR pInst, T5_PTWORD pArgs);

